"""“urls”

Revision ID: fa56cec33279
Revises: 86fd662e0337
Create Date: 2022-10-19 09:23:41.453646

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "fa56cec33279"
down_revision = "86fd662e0337"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("urls", "key", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint(op.f("uq_urls_key"), "urls", ["key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_urls_key"), "urls", type_="unique")
    op.alter_column("urls", "key", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
