"""urls

Revision ID: b80f0f4115bb
Revises: 89d72c1f9a9c
Create Date: 2022-10-27 15:07:10.224732

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b80f0f4115bb'
down_revision = '89d72c1f9a9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('urls', 'target_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('target_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('urls', 'url')
    # ### end Alembic commands ###
