"""“urls”

Revision ID: 2ba4f9045b91
Revises: fa56cec33279
Create Date: 2022-10-19 10:47:25.683112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "2ba4f9045b91"
down_revision = "fa56cec33279"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
